spring:
  application:
    name: audio-storage-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  main:
    banner-mode: off
  docker:
    compose:
      file: src/main/docker/compose.yml

logging:
  level:
    com.acltabontabon: INFO
