[versions]
spring_boot = "3.3.0"
spring_boot_dependency_mgmt = "1.1.6"

[plugins]
springBootPlugin = { id = "org.springframework.boot", version.ref = "spring_boot" }
springBootDependencyMgmtPlugin = { id = "io.spring.dependency-management", version.ref = "spring_boot_dependency_mgmt" }